In [10]:
import numpy as np

In [11]:
# A=np.zeros([10,10])

In [21]:
# c = np.arange(11,20)
# a = np.arange(1,11)
# e = np.arange(102,111)
rows=3
cols=3
ones = np.ones(rows*cols)

A = np.diag(4*ones) + np.diag(-1*ones[:-1],-1) + np.diag(-1*ones[:-1],1) + np.diag(-1*ones[:-cols],-cols) + np.diag(-1*ones[:-cols],cols)


# A = np.diag(c,1) + np.diag(a) + np.diag(e,-1)

# B = np.diag(4) + np.diag()

In [22]:
A

array([[ 4., -1.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  4., -1.,  0., -1.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  4., -1.,  0., -1.,  0.,  0.,  0.],
       [-1.,  0., -1.,  4., -1.,  0., -1.,  0.,  0.],
       [ 0., -1.,  0., -1.,  4., -1.,  0., -1.,  0.],
       [ 0.,  0., -1.,  0., -1.,  4., -1.,  0., -1.],
       [ 0.,  0.,  0., -1.,  0., -1.,  4., -1.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0., -1.,  4., -1.],
       [ 0.,  0.,  0.,  0.,  0., -1.,  0., -1.,  4.]])

In [90]:
b = np.ones([10])

In [91]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [116]:
alpha=np.zeros(len(A))
beta=np.zeros(len(A)-1)
y=np.zeros(len(A))
x=np.zeros(len(A))
alpha[0]=a[0]
y[0]=b[0]
for i in range(len(A)-1):
    beta[i] = e[i]/alpha[i]
    alpha[i+1]=a[i+1]-beta[i]*c[i]
    y[i+1] = b[i+1] - beta[i]*y[i]
    

In [117]:
alpha
beta

array([ 1.02000000e+02, -9.19642857e-02,  2.53437772e+01, -3.22611267e-01,
        1.11384813e+01, -6.64277673e-01,  6.12646287e+00, -1.13364689e+00,
        3.74077846e+00])

In [118]:
x[len(A)-1]=y[len(A)-1]/alpha[len(A)-1]
for i in range(len(A)-1)[::-1]:
    x[i] = y[i] - c[i]*x[i+1]


In [119]:
x

array([-1.33110395e+12,  1.21009450e+11, -1.00841208e+10,  7.75701601e+08,
       -5.54072422e+07,  3.69382075e+06, -2.30911832e+05,  1.35530762e+04,
       -5.79467860e+02,  2.16866089e+02])

In [120]:
y

array([ 1.00000000e+00, -1.01000000e+02, -8.28839286e+00,  2.11059182e+02,
        6.90900702e+01, -7.68558451e+02, -5.09536219e+02,  3.12265473e+03,
        3.54098783e+03, -1.32450510e+04])

In [121]:
np.matmul(A,x)

array([ 1.00000000e+00, -1.35651593e+14,  1.24438051e+13, -1.04642146e+12,
        8.12270392e+10, -5.85469933e+09,  3.93852840e+08, -2.48404836e+07,
        1.47619055e+06, -6.15728037e+04])